### ISSUE TITLE
Node 16 error on Github workflow

### ISSUE THREAD

**Issue by gasigo** [Cyberbeni/install-swift-tool#113]
After the last update our lint workflow is failing consistently. This is the output we get: 

`System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')
`

Any help is appreciated.

**Comment by Cyberbeni** [comment]
node16 support was added 2 days ago to the runner: https://github.com/actions/runner/releases/tag/v2.285.0

Are you using self hosted runners? Updating it will solve the issue.

I haven't seen any sign of them having a staged rollout (and it ran fine when I tested running with node16) that would result in node16 not being available for everyone.

As there are no critical changes in the newest release, I reverted the v2 tag to point to the previous release until this issue is resolved.

**Comment by gasigo** [comment]
We're not using self hosted runners. But reverting the v2 tag fixed the issue for me.

**Comment by Cyberbeni** [comment]
The first line of the set up prints which version of the runner you have, I assume that is 2.184.0 for the failed workflows, right?

For example the PR workflow ran with 2.185.0 for me: https://github.com/Cyberbeni/install-swift-tool/runs/4384620950?check_suite_focus=true#step:1:1

I'll open an issue for them to provide information about staged rollout progress, like they have for virtual environments: https://github.com/actions/virtual-environments#available-environments

**Comment by Cyberbeni** [comment]
node16 should be available to everyone by now, so I updated the v2 branch to use that as node12 will stop getting security updates on April 30.
